<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date From-To_basic_date</name>
   <tag></tag>
   <elementGuidId>39164970-8c47-4a80-b0b5-eef822cea8f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c816e685-cfc4-428a-b4be-81793139e00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_date</value>
      <webElementGuid>7265edf6-6bfb-422b-943b-f5c811cb4060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>From Date</value>
      <webElementGuid>8a0eea53-38ce-4d70-b4e8-6c7f31a9167d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>5d80c5de-4ace-46b8-bfe6-08549e320bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>50b3de3e-af6e-48ab-b65b-64456963514e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_date&quot;)</value>
      <webElementGuid>61d22f42-1806-4d52-82f3-330e92ff18bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_date']</value>
      <webElementGuid>ff06181a-e70c-4348-9a34-d7c0b77bb288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[2]/div[2]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>7b46a8bf-fb9a-4a3a-8a62-5b418c2a53f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>38be81d4-e22e-4c15-bf3b-30ba58af90a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_date' and @placeholder = 'From Date']</value>
      <webElementGuid>8c5a9dc8-192e-4946-944d-f42e051d1321</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
