<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Annual Leave Hours_basic_annualLeaveHours</name>
   <tag></tag>
   <elementGuidId>fe56b46d-d95b-4df9-a0fe-32039e57627c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_annualLeaveHours</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_annualLeaveHours']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>857dfc61-9e08-43e7-b082-bf53d8089e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c9630103-dfaf-4f15-a5cc-0909e64c5c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>c4b30814-5751-4fd1-a1e7-47d19f9af0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>392870b6-adba-4abb-896f-0f4da68508ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e328ed95-0a27-4f3e-8526-38a5835d4f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>32cd6de3-8e24-46cc-ba24-656b9ac77f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter annual leave hour(s)</value>
      <webElementGuid>aa93f23b-b649-484f-9e72-cd0740dcf8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_annualLeaveHours</value>
      <webElementGuid>5da543c6-6992-43ad-b471-e0497ca6fc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-number-input</value>
      <webElementGuid>386fe949-37ae-44d1-84f9-c995a660b953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>73ecc618-aedc-4b57-a9d8-018ad2261634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_annualLeaveHours&quot;)</value>
      <webElementGuid>83ef80d0-c105-4626-96e7-827ce22cfb3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_annualLeaveHours']</value>
      <webElementGuid>707d32c8-4c4a-49dc-9416-45dfd0cb3f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[4]/div/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>b67dd74b-3a3a-4c23-908a-d0ebcbcc8eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>ef918fd7-c492-4c85-ad00-7d4465d0596f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Please enter annual leave hour(s)' and @id = 'basic_annualLeaveHours']</value>
      <webElementGuid>eeecf442-de00-4318-b8d7-a611edaf3427</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
