<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sick Leave Hours_basic_sickLeaveHours</name>
   <tag></tag>
   <elementGuidId>bee8fbe2-f95e-44c7-825a-121deb6c74ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_sickLeaveHours</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_sickLeaveHours']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00a3a12f-e3cf-481b-9d5e-86b5c72ee88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4ea84fc7-1d6b-4bd4-9660-ab60843f0c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>d34e1ae5-0d02-47f2-b141-899cca7460ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b2b396e5-22db-4b46-bf43-bd41e17d2e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>29f83193-affd-4fe9-bad1-a20082a92046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>237a7abe-058d-4d53-be0e-fbd861f149fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter sick leave hour(s)</value>
      <webElementGuid>c0f4ae31-6031-4ffb-bed7-2dd7a6ceeabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_sickLeaveHours</value>
      <webElementGuid>f8f0c8f9-90b2-4abd-a978-232cc8e87dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-number-input</value>
      <webElementGuid>f48cc578-371f-4ab4-bbaf-3db152dd07b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cf55bb76-bf2c-478b-b407-75695e2fa979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_sickLeaveHours&quot;)</value>
      <webElementGuid>7ff67825-588b-4357-a799-4570a0d1fe81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_sickLeaveHours']</value>
      <webElementGuid>54deeaaa-cc06-42a4-9d21-6ed55c6cb6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[4]/div[2]/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>404d8506-cbe3-4710-8853-193599f8ba28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>64563927-262b-48ac-aea0-65ce14b26862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Please enter sick leave hour(s)' and @id = 'basic_sickLeaveHours']</value>
      <webElementGuid>8f8c01c7-50fd-4a79-a3d3-2071af9b73de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
